// js/catalog.js
(function (root, factory) {
  if (typeof module === 'object' && module.exports) {
    module.exports = factory();
  } else {
    root.Catalog = factory();
  }
})(typeof self !== 'undefined' ? self : this, function () {
  const MENU = [
    { slug: '3-autores', name: '3 Autores', category: 'Tinto', price: 57.64, country: 'Portugal', grape: 'Blend', image: 'img/3-autores.jpg', description: 'O 3 Autores D.O.C. Tinto é muito mais do que um vinho; é a expressão do talento e da paixão de três figuras essenciais da Vidigal Wines. Criado sob a supervisão de António Mendes Lopes, António Ventura e Rafael Neuparth', abv: 13.5, pairings: ['Carnes', 'Massas', 'Bacalhau'] },
    { slug: 'adega-grande-rose', name: 'Adega Grande Rosé', category: 'Rosé', price: 45.35, country: 'Portugal', grape: 'Blend', image: 'img/adega-grande-rose.jpg', description: 'O Adega Grande Rosé possui um rosa marcante no visual, trazendo no olfato frutas vermelhas maduras como morango, ameixa e cereja, além de notas florais de rosas.', abv: 10.5, pairings: ['Frutos do Mar', 'Frango', 'Peixes'] },
    { slug: 'amo-te-tinto', name: 'Amo-te tinto', category: 'Tinto', price: 60.65, country: 'Portugal', grape: 'Blend', image: 'img/amo-te-tinto.jpg', description: 'O Amo-te Tinto é produzido em Portugal e combina fruta madura, suavidade e equilíbrio, resultando em um vinho envolvente e cheio de charme. Seu perfil aromático e seus taninos macios tornam-no perfeito para momentos especiais.', abv: 13.0, pairings: ['Carnes', 'Massas', 'Bacalhau'] },
    { slug: 'ancelotta-giaretta', name: 'Ancelotta Giaretta', category: 'Tinto', price: 38.4, country: 'Brasil', grape: 'Ancellotta', image: 'img/ancelotta-giaretta.jpg', description: 'Esse Ancellotta representa água. Outrora utilizado apenas para cortes ou blends numa mudança da água para o vinho, atualmente é um varietal rico, com alto potencial de envelhecimento.', abv: 12.5, pairings: ['Carnes', 'Massas', 'Pizza'] },
    { slug: 'arinarmoa-giaretta', name: 'Arinarmoa Giaretta', category: 'Tinto', price: 67.1, country: 'Brasil', grape: 'Arinarnoa', image: 'img/arinarmoa-giaretta.jpg', description: 'O Giaretta Reserva Arinarnoa nasce na Campanha Gaúcha e destaca uma uva rara e cheia de identidade: a Arinarnoa, batizada a partir do basco “arin” (leve) + “arnoa” (vinho). Reconhecida como um cruzamento de Tannat com Cabernet Sauvignon, ela costuma entregar cor intensa, boa estrutura e um perfil gastronômico.', abv: 13.8, pairings: ['Carnes', 'Pizza', 'Massas'] },
    { slug: 'artolas-branco', name: 'Artolas Branco', category: 'Branco', price: 41.16, country: 'Portugal', grape: 'Blend', image: 'img/artolas-branco.jpg', description: 'O Artolas Branco, produzido pela renomada vinícola Artolas, é a perfeita expressão da tradição e inovação da vitivinicultura portuguesa. Com um blend único das uvas Fernão Pires, Arinto e Sauvignon Blanc', abv: 12.0, pairings: ['Saladas', 'Frutos do Mar', 'Peixes'] },
    { slug: 'baron-philippe-de-rothschild-reserva-especial-merlot', name: 'Baron Philippe de Rothschild Reserva Especial Merlot', category: 'Tinto', price: 65.55, country: 'França', grape: 'Merlot', image: 'img/baron-philippe-de-rothschild-reserva-especial-merlot.jpg', description: 'Baron Philippe de Rothschild Reserva Especial Merlot é um tinto macio e elegante, perfeito para quem gosta de vinhos fáceis de beber, mas com presença. No aroma, traz frutas vermelhas e negras maduras (ameixa, cereja, amora) com um toque delicado de baunilha e especiarias', abv: 13.0, pairings: ['Carnes', 'Pizza', 'Ensopados'] },
    { slug: 'bianco-toscana-igt-rifugio-del-vescovo', name: 'Bianco Toscana Igt Rifugio Del Vescovo', category: 'Branco', price: 95.65, country: 'Itália', grape: 'Blend', image: 'img/bianco-toscana-igt-rifugio-del-vescovo.jpg', description: 'O Bianco Toscana IGT Rifugio Del Vescovo une tradição e leveza em um branco vibrante, perfeito para momentos especiais ou para transformar o dia a dia em celebração.', abv: 11.5, pairings: ['Frutos do Mar', 'Peixes', 'Ceviche'] },
    { slug: 'boa-noite-lisboa', name: 'Boa Noite Lisboa', category: 'Tinto', price: 55.35, country: 'Portugal', grape: 'Blend', image: 'img/boa-noite-lisboa.jpg', description: 'O Boa Noite Liksboa, da região de Lisboa, combina duas uvas que se complementam muito bem: a Syrah, intensa e envolvente, que entrega corpo estruturado, notas de frutas negras, especiarias e um toque de pimenta-preta, e a Touriga Nacional, elegante e aromática', abv: 14.0, pairings: ['Carnes', 'Bacalhau', 'Pizza'] },
    { slug: 'bodega-torrontes', name: 'Bodega Torrontés', category: 'Branco', price: 56.88, country: 'Argentina', grape: 'Torrontés', image: 'img/bodega-torrontes.jpg', description: 'Perfeito para dias quentes, varanda/happy hour e brunch. Vai muito bem com ceviche, frutos do mar, sushi, saladas aromáticas, empanadas, queijos leves e pratos com toque cítrico/agridoce.', abv: 12.8, pairings: ['Ceviche', 'Saladas', 'Frutos do Mar'] },
    { slug: 'bridao-merlot', name: 'Bridão Merlot', category: 'Tinto', price: 103.56, country: 'Imperial', grape: 'Merlot', image: 'img/bridao-merlot.jpg', description: 'O Bridão Merlot 2017 é um tinto de perfil redondo e convidativo, com a Merlot mostrando seu lado mais macio: frutas vermelhas e negras maduras, leve toque de especiarias e uma textura aveludada que deixa o vinho fácil de beber.', abv: 14.0, pairings: ['Carnes', 'Pizza', 'Ensopados'] },
    { slug: 'buenardo-malbec-vinho-organico', name: 'Buenardo Malbec Vinho Orgânico', category: 'Tinto', price: 75.3, country: 'Argentina', grape: 'Malbec', image: 'img/buenardo-malbec-vinho-organico.jpg', description: 'Um vinho com certificação orgânica, onde as frutas mais frescas são evidenciadas. Elaborado com a casta Malbec, é uma excelente opção de custo-benefício para quem deseja experimentar um vinho orgânico.', abv: 13.3, pairings: ['Carnes', 'Pizza', 'Ensopados'] },
    { slug: 'ca-montebello-barbera', name: 'Cà Montebello BARBERA', category: 'Tinto', price: 87.03, country: 'Itália', grape: 'Barbera', image: 'img/ca-montebello-barbera.jpg', description: 'O Cà Montebello Barbera revela toda a força da uva Barbera, uma das mais tradicionais da Itália. Com aromas de frutas vermelhas maduras, notas sutis de especiarias e acidez vibrante, é um vinho cheio de caráter e autenticidade', abv: 13.5, pairings: ['Massas', 'Pizza', 'Carnes'] },
    { slug: 'ca-montebello-pinot-nero', name: 'Cà Montebello Pinot Nero', category: 'Tinto', price: 80.24, country: 'Itália', grape: 'Pinot Noir', image: 'img/ca-montebello-pinot-nero.jpg', description: 'Direto da Lombardia, na Itália, este Pinot Noir — conhecido como Pinot Nero traz elegância e suavidade. Um vinho ideal para impressionar em encontros românticos e jantares especiais. Delicado, aromático e com muito charme italiano.', abv: 13.0, pairings: ['Peixes', 'Charcutaria', 'Carnes'] },
    { slug: 'calvet-varietals-merlot', name: 'Calvet Varietals Merlot', category: 'Tinto', price: 68.71, country: 'França', grape: 'Merlot', image: 'img/calvet-varietals-merlot.jpg', description: 'O Calvet Varietals Merlot combina elegância e acessibilidade em um tinto redondo e frutado, perfeito para acompanhar do jantar descontraído ao encontro especial.', abv: 13.5, pairings: ['Queijos', 'Carnes', 'Pizza'] },
    { slug: 'castas-diferenciadas-cabernet-franc', name: 'Castas Diferenciadas Cabernet Franc', category: 'Tinto', price: 66.08, country: 'Brasil', grape: 'Cabernet Franc', image: 'img/castas-diferenciadas-cabernet-franc.jpg', description: 'A Cabernet Franc foi uma das uvas que despertou meu interesse pelo mundo dos vinhos. Conhecida por produzir rótulos extremamente equilibrados, é uma excelente escolha para quem busca um vinho versátil e sofisticado.', abv: 13.9, pairings: ['Carnes', 'Charcutaria', 'Queijos'] },
    { slug: 'castas-diferenciadas-gewurztraminer', name: 'Castas Diferenciadas Gewurztraminer', category: 'Branco', price: 50.22, country: 'Brasil', grape: 'Gewurztraminer', image: 'img/castas-diferenciadas-gewurztraminer.jpg', description: 'A Gewürztraminer, uma das uvas brancas mais emblemáticas da Alemanha e da Alsácia Francesa, encontrou no Brasil um terroir perfeito para expressar sua autenticidade.', abv: 12.7, pairings: ['Ceviche', 'Frutos do Mar', 'Saladas'] },
    { slug: 'cavic-malbec', name: 'Cavic Malbec', category: 'Tinto', price: 47.7, country: 'Argentina', grape: 'Malbec', image: 'img/cavic-malbec.jpg', description: 'Um Malbec vibrante e acessível, que revela o melhor da expressão frutada e envolvente desta casta emblemática.', abv: 12.5, pairings: ['Carnes', 'Pizza', 'Ensopados'] },
    { slug: 'chardonnay-giaretta', name: 'Chardonnay Giaretta', category: 'Branco', price: 40.07, country: 'Brasil', grape: 'Chardonnay', image: 'img/chardonnay-giaretta.jpg', description: 'Um branco brasileiro elegante e versátil, que traduz frescor e equilíbrio em cada taça.', abv: 12.5, pairings: ['Frutos do Mar', 'Peixes', 'Ceviche'] },
    { slug: 'chateau-bel-enclos', name: 'Château Bel Enclos', category: 'Tinto', price: 59.63, country: 'França', grape: 'Blend', image: 'img/chateau-bel-enclos.jpg', description: 'O Château Bel Enclos – Côtes de Bordeaux é um tinto elegante e acessível, premiado com Medalha de Ouro em 2023, que traz notas de frutas negras maduras, taninos macios e um final aveludado. Um vinho que une tradição e sofisticação na medida certa.', abv: 13.5, pairings: ['Ensopados', 'Carnes', 'Pizza'] },
    { slug: 'chateau-jamin-bourdeaux', name: 'Château Jamin Bourdeaux', category: 'Tinto', price: 58.74, country: 'França', grape: 'Blend', image: 'img/chateau-jamin-bourdeaux.jpg', description: 'CHÂTEAU JAMIN BORDEAUX 2021 é um tinto francês que traduz bem o “jeito Bordeaux” de fazer vinho: equilíbrio, elegância e facilidade de beber. No aroma, aparecem frutas escuras (como ameixa e amora) com um toque delicado de especiarias e leve nuance terrosa', abv: 13.0, pairings: ['Carnes', 'Queijos', 'Pizza'] },
    { slug: 'chateau-maine-d-arman-cotes-de-bourg-aoc', name: 'Château Maine D\'Arman - Côtes de Bourg AOC', category: 'Tinto', price: 123.35, country: 'França', grape: 'Blend', image: 'img/chateau-maine-d-arman-cotes-de-bourg-aoc.jpg', description: 'Jantares de carnes, queijos & charcutaria, massas ao ragu/risotos, pratos de panela, churrasco ao entardecer e dias frios. Ótimo para jantar de negócios e para presentear.', abv: 14.0, pairings: ['Carnes', 'Queijos', 'Pizza'] },
    { slug: 'chavarri-larchago-rioja-doca', name: 'Chavarri - Larchago - Rioja DOCa', category: 'Tinto', price: 113.86, country: 'Espanha', grape: 'Tempranillo', image: 'img/chavarri-larchago-rioja-doca.jpg', description: 'Uma homenagem à tradição vinícola de Rioja, unindo juventude e elegância. Aromas vibrantes de frutas vermelhas maduras, especiarias sutis e um toque tostado.', abv: 14.0, pairings: ['Charcutaria', 'Queijos', 'Pizza'] },
    { slug: 'chianti-rifugio-del-vescovo', name: 'Chianti Rifugio Del Vescovo', category: 'Tinto', price: 86.65, country: 'Itália', grape: 'Sangiovese', image: 'img/chianti-rifugio-del-vescovo.jpg', description: 'Clássico toscano que combina elegância e acidez vibrante. Aromas de frutas vermelhas, ervas secas e leve toque terroso.', abv: 13.0, pairings: ['Massas', 'Pizza', 'Carnes'] },
    { slug: 'coragem-reserva', name: 'Coragem Reserva', category: 'Tinto', price: 74.25, country: 'Portugal', grape: 'Blend', image: 'img/coragem-reserva.jpg', description: 'O Coragem Reserva é aquele tinto português feito para agradar sem esforço: chega com fruta madura na medida, um toque sutil de especiarias e uma estrutura firme, mas macia, que acompanha bem a mesa.', abv: 13.5, pairings: ['Bacalhau', 'Carnes', 'Pizza'] },
    { slug: 'corinto-carmenere-2021', name: 'Corinto Carmenere – 2021', category: 'Tinto', price: 53.06, country: 'Chile', grape: 'Carménère', image: 'img/corinto-carmenere-2021.jpg', description: 'Um varietal elegante que transforma qualquer momento em uma ocasião especial.', abv: 13.0, pairings: ['Carnes', 'Queijos', 'Pizza'] },
    { slug: 'corinto-reserva-cabernet-sauvignon-2018', name: 'Corinto Reserva Cabernet Sauvignon – 2018', category: 'Tinto', price: 58.93, country: 'Chile', grape: 'Cabernet Sauvignon', image: 'img/corinto-reserva-cabernet-sauvignon-2018.jpg', description: 'Este Cabernet Sauvignon reserva de cor púrpura intenso tem aroma de frutas vermelhas, especialmente cereja e ameixa, com tons de ervas, especiarias, como estragão e pimenta preta, tabaco e baunilha. Paladar bem balanceado, excelente estrutura e final médio a longo. Harmoniza perfeitamente com carnes vermelhas.', abv: 13.0, pairings: ['Carnes', 'Queijos', 'Ensopados'] },
    { slug: 'dedicato-blanc-de-blancs-brut', name: 'Dedicato Blanc de Blancs Brut', category: 'Espumante', price: 63.16, country: 'Itália', grape: 'Blend', image: 'img/dedicato-blanc-de-blancs-brut.jpg', description: 'O Dedicato Blanc de Blancs Brut é um espumante elegante e refrescante, perfeito para quem gosta de um estilo mais leve e fácil de beber. Ele traz notas delicadas de frutas brancas e cítricas, com borbulhas finas, boa acidez e final bem equilibrado', abv: 11.5, pairings: ['Frutos do Mar', 'Ceviche', 'Saladas'] },
    { slug: 'deinhard-green-label-riesling', name: 'Deinhard Green Label Riesling', category: 'Branco', price: 83.35, country: 'Alemanha', grape: 'Riesling', image: 'img/deinhard-green-label-riesling.jpg', description: 'O Deinhard Green Label Riesling é fresco, aromático e equilibrado, trazendo notas frutadas e acidez vibrante que encantam em qualquer ocasião.', abv: 10.5, pairings: ['Frutos do Mar', 'Peixes', 'Saladas'] },
    { slug: 'dufouleur-monopole-rose', name: 'Dufouleur Monopole Rosé', category: 'Rosé', price: 58.85, country: 'França', grape: 'Blend', image: 'img/dufouleur-monopole-rose.jpg', description: 'Um rosé para quem gosta de frescor com sabor de fruta. O Dufouleur Monopole Rosé traz aromas e sabores de frutas vermelhas destaque para framboesa e groselha vermelha com uma acidez suave que deixa tudo mais gostoso e convidativ', abv: 11.5, pairings: ['Frutos do Mar', 'Peixes', 'Ceviche'] },
    { slug: 'emersao-merlot', name: 'Emersão - Merlot', category: 'Tinto', price: 113.79, country: 'Brasil', grape: 'Merlot', image: 'img/emersao-merlot.jpg', description: 'Conheci a linha de vinhos Emersão, da vinícola Cárdenas, durante a degustação do Pássaro da Lua, e foi uma agradável surpresa descobrir que essa vinícola também possui outros rótulos de altíssima qualidade. O Emersão Merlot surpreende a cada gole: é um vinho fácil de beber e extremamente gastronômico, ideal para acompanhar pratos mais suculentos e untuosos.', abv: 12.7, pairings: ['Carnes', 'Pizza', 'Queijos'] },
    { slug: 'emersao-syrah', name: 'Emersão - Syrah', category: 'Tinto', price: 129.54, country: 'Brasil', grape: 'Syrah', image: 'img/emersao-syrah.jpg', description: 'O Emersão Syrah 2019, da Serra do Sudeste, é um tinto encorpado e imponente, com notas complexas de frutas negras, couro, especiarias e final longo e marcante.', abv: 12.3, pairings: ['Carnes', 'Ensopados', 'Queijos'] },
    { slug: 'emersao-blend', name: 'Emersão Blend', category: 'Tinto', price: 129.94, country: 'Brasil', grape: 'Blend', image: 'img/emersao-blend.jpg', description: 'Conheci a linha de vinhos Emersão, da vinícola Cárdenas, durante a degustação do Pássaro da Lua, e foi uma agradável surpresa descobrir que essa vinícola também possui outros rótulos de altíssima qualidade.', abv: 8.0, pairings: ['Carnes', 'Pizza', 'Queijos'] },
    { slug: 'excelso-reserva-cabernet-sauvignon', name: 'Excelso Reserva Cabernet Sauvignon', category: 'Tinto', price: 83.55, country: 'Chile', grape: 'Cabernet Sauvignon', image: 'img/excelso-reserva-cabernet-sauvignon.jpg', description: 'Perfeito para jantares de carnes (bife, costela ao forno), massas ao molho vermelho e pizza de calabresa. Acompanha hambúrguer artesanal e queijos semicurados. Vai bem no churrasco de fim de semana, em encontros com amigos e como presente clássico para quem gosta de tintos fáceis de agradar.', abv: 14.0, pairings: ['Carnes', 'Ensopados', 'Queijos'] },
    { slug: 'fincas-privada-bornarda', name: 'Fincas Privada Bornarda', category: 'Tinto', price: 49.93, country: 'Argentina', grape: 'Bonarda', image: 'img/fincas-privada-bornarda.jpg', description: 'Ótimo para almoço de domingo, massas e pizzas (molho de tomate), empanadas, carnes grelhadas e churrasco leve. Vai bem em encontros com amigos e como tinto do dia a dia para quem gosta de vinhos frutados, macios e fáceis de beber.', abv: 13.0, pairings: ['Carnes', 'Pizza', 'Queijos'] },
    { slug: 'flor-d-penalva', name: 'Flor D\'Penalva', category: 'Tinto', price: 71.97, country: 'Portugal', grape: 'Blend', image: 'img/flor-d-penalva.jpg', description: 'O Flor D’Penalva é um tinto português do Dão (Penalva do Castelo), conhecido pelo estilo elegante e gastronômico da região: costuma ser feito com castas locais como Tinta Roriz, Jaen e Alfrocheiro, entregando cor rubi, aromas de frutas vermelhas e silvestres com um toque floral', abv: 13.0, pairings: ['Bacalhau', 'Carnes', 'Pizza'] },
    { slug: 'fonte-da-perdiz-branco-d-o-c', name: 'Fonte da Perdiz Branco D.O.C.', category: 'Tinto', price: 50.79, country: 'Portugal', grape: 'Blend', image: 'img/fonte-da-perdiz-branco-d-o-c.jpg', description: 'Imagine as encostas do majestoso Vale do Douro, em Portugal, onde o sol beija as videiras e os ventos frescos conferem caráter único às uvas.', abv: 12.5, pairings: ['Peixes', 'Frutos do Mar', 'Ceviche'] },
    { slug: 'frisante-almaden-moscatel-rose', name: 'Frisante Almadén Moscatel Rosé', category: 'Rosé', price: 31.01, country: 'Brasil', grape: 'Moscatel', image: 'img/frisante-almaden-moscatel-rose.jpg', description: 'O Frisante Almadén Moscatel Rosé é uma verdadeira celebração da vinicultura brasileira, trazendo um frescor irresistível e um toque frutado que encanta os apreciadores de vinhos leves e aromáticos', abv: 7.0, pairings: ['Peixes', 'Frutos do Mar', 'Ceviche'] },
    { slug: 'gretus-tempranillo', name: 'Gretus Tempranillo', category: 'Tinto', price: 48.59, country: 'Espanha', grape: 'Tempranillo', image: 'img/gretus-tempranillo.jpg', description: 'Perfeito para noite de massas e pizzas (molho de tomate), tapas/embutidos, queijos semicurados, hambúrguer e carnes grelhadas no churrasco leve. Vai bem em encontros com amigos, jantar informal e como presente descomplicado para quem curte tintos frutados e macios.', abv: 12.5, pairings: ['Pizza', 'Massas', 'Embutidos'] },
    { slug: 'herdade-do-gamito-tinto-alicante-bouschet', name: 'Herdade do Gamito tinto Alicante Bouschet', category: 'Tinto', price: 96.97, country: 'Portugal', grape: 'Alicante Bouschet', image: 'img/herdade-do-gamito-tinto-alicante-bouschet.jpg', description: 'O Herdade do Gamito Tinto – Alicante Bouschet é um vinho alentejano de personalidade marcante, elaborado com uma das uvas mais emblemáticas de Portugal. Apresenta aromas de frutas negras maduras, especiarias e notas de cacau, entregando um tinto encorpado, de taninos firmes e final persistente.', abv: 14.5, pairings: ['Carnes', 'Ensopados', 'Massas'] },
    { slug: 'herdade-grande-origens', name: 'Herdade Grande Origens', category: 'Tinto', price: 57.82, country: 'Portugal', grape: 'Não informado', image: 'img/herdade-grande-origens.jpg', description: 'Oriundo do Alentejo, uma das regiões mais tradicionais de Portugal, este blend, composto pelas uvas Aragonez, Trincadeira e Alfrocheiro, traz uma robustez típica dos vinhos portugueses, com um excelente custo-benefício.', abv: 14.0, pairings: ['Bacalhau', 'Pizza', 'Carnes'] },
    { slug: 'iciottoli-cabernet-sauvignon', name: 'Iciottoli Cabernet Sauvignon', category: 'Tinto', price: 92.91, country: 'Itália', grape: 'Cabernet Sauvignon', image: 'img/iciottoli-cabernet-sauvignon.jpg', description: 'Descubra a intensidade do Cabernet Sauvignon italiano! O Iciottoli Cabernet Sauvignon revela um tinto elegante e estruturado, marcado por notas de frutas maduras, especiarias e taninos aveludados que elevam qualquer ocasião.', abv: 13.0, pairings: ['Massas', 'Pizza', 'Ossobuco'] },
    { slug: 'intimista', name: 'Intimista', category: 'Tinto', price: 39.27, country: 'Portugal', grape: 'Blend', image: 'img/intimista.jpg', description: 'O Vinho Intimista é aquele rótulo feito para momentos mais tranquilos e especiais, quando você quer curtir sem pressa e com uma taça que combina com o clima. Ele tem um perfil macio, equilibrado e fácil de gostar, trazendo notas de frutas maduras e um toque elegante no final.', abv: 13.0, pairings: ['Carnes', 'Embutidos', 'Salgados'] },
    { slug: 'ique-vegano', name: 'Ique Vegano', category: 'Branco', price: 50.98, country: 'Argentina', grape: 'Malbec', image: 'img/ique-vegano.jpg', description: 'Descubra o IQUE Malbec, um vinho argentino vegano que expressa toda a riqueza do Vale de Uco, Mendoza. Produzido a partir de uvas 100% Malbec, cultivadas a 1.050 metros de altitude, este rótulo é a perfeita combinação entre frescor, autenticidade e sofisticação. Um Malbec Diferenciado.', abv: 12.8, pairings: ['Churrasco', 'Pizza', 'Ensopados'] },
    { slug: 'julia-florista-reserva', name: 'Júlia Florista Reserva', category: 'Tinto', price: 59.86, country: 'Portugal', grape: 'Blend', image: 'img/julia-florista-reserva.jpg', description: 'O Julia Florista Reserva é um tinto português cheio de personalidade, que combina fruta madura, notas sutis de especiarias e taninos macios, resultando em um vinho envolvente e equilibrado.', abv: 13.0, pairings: ['Lanches', 'Carnes', 'Pizza'] },
    { slug: 'la-treille-de-candale', name: 'La Treille De Candale', category: 'Tinto', price: 57.59, country: 'França', grape: 'Blend', image: 'img/la-treille-de-candale.jpg', description: 'O La Treille de Candale é elaborado com a uva Tempranillo na região de Saint Jean d’Ardières, trazendo um tinto equilibrado e elegante, com notas de frutas vermelhas maduras, especiarias delicadas e taninos macios que tornam cada gole uma experiência prazerosa', abv: 13.0, pairings: ['Carnes', 'Embutidos', 'Pizza'] },
    { slug: 'lacase-carmenere', name: 'Lacaze Carménére', category: 'Tinto', price: 49.76, country: 'França', grape: 'Carménère', image: 'img/lacase-carmenere.jpg', description: 'Um chileno de alma intensa e coração macio, cheio de charme e personalidade. Aromas frutados, com notas de frutas vermelhas maduras e especiarias sutis. Paladar redondo, macio e envolvente, com equilíbrio e persistência.', abv: 13.0, pairings: ['Carnes', 'Lanches', 'Salgados'] },
    { slug: 'lambrusco-d-emilia-amabile-bco-suave', name: 'Lambrusco D\'Emilia – Amabile - Bco Suave', category: 'Branco', price: 42.42, country: 'Itália', grape: 'Lambrusco', image: 'img/lambrusco-d-emilia-amabile-bco-suave.jpg', description: 'Leve, borbulhante e refrescante, é o vinho que transforma encontros simples em celebração. Vai bem na varanda ao fim da tarde, em almoços descontraídos de fim de semana ou como “primeira taça” para abrir os trabalhos. A fruta branca aparece crocante, a doçura é delicada e as borbulhas deixam tudo mais fácil de beber', abv: 8.0, pairings: ['Frutos do Mar', 'Saladas', 'Peixes'] },
    { slug: 'lambrusco-d-emilia-amabile-tinto-suave', name: 'Lambrusco D\'Emilia – Amabile - Tinto  Suave', category: 'Tinto', price: 42.42, country: 'Itália', grape: 'Lambrusco', image: 'img/lambrusco-d-emilia-amabile-tinto-suave.jpg', description: 'Leve, frutado e com borbulhas que animam — perfeito para reunir amigos sem cerimônia. A fruta vermelha (morangos, framboesas) aparece fresca, a doçura é sutil e a acidez mantém tudo fácil de beber. Vai da “primeira taça” ao brinde final sem cansar', abv: 8.0, pairings: ['Massas', 'Carnes', 'Frango'] },
    { slug: 'late-harverst-miolo', name: 'Late Harverst Miolo', category: 'Sobremesa', price: 62.1, country: 'Brasil', grape: 'Blend', image: 'img/late-harverst-miolo.jpg', description: 'Imagine um pôr do sol dourado sobre os vinhedos da Campanha Gaúcha, onde cada cacho de uva é colhido no momento exato para capturar a essência da doçura natural. É nesse cenário encantador que nasce o Miolo Late Harvest Licoroso Branco, um vinho de sobremesa que transforma cada taça em uma experiência única e inesquecível.', abv: 15.5, pairings: ['Bolos', 'Mouse', 'Frutas'] },
    { slug: 'lomas-del-marques-tempranillo', name: 'Lomas Del Marques Tempranillo', category: 'Tinto', price: 51.37, country: 'Espanha', grape: 'Tempranillo', image: 'img/lomas-del-marques-tempranillo.jpg', description: 'O Lomas del Marqués Tempranillo nasce na lendária Rioja, uma das poucas regiões da Espanha com a rigorosa Denominación de Origen Calificada (DOCa), selo reservado a áreas de excelência e controle de qualidade mais exigente.', abv: 13.0, pairings: ['Embutidos', 'Carnes', 'Pizza'] },
    { slug: 'marselan-giaretta', name: 'Marselan Giaretta', category: 'Tinto', price: 51.76, country: 'Brasil', grape: 'Marselan', image: 'img/marselan-giaretta.jpg', description: 'A ampulheta e o tempo, tempo que aprimora o vinho criando e recriando sensações diferentes, em momentos distintos. Da mesma forma que o ser humano, o vinho nasce jovem e se transforma no que precisa ser, respeitando as leis da vida.', abv: 12.8, pairings: ['Carnes', 'Pizza', 'Queijos'] },
    { slug: 'martha-s-moscatel-do-douro', name: 'Martha\'s MOSCATEL do DOURO', category: 'Tinto', price: 70.8, country: 'Portugal', grape: 'Moscatel', image: 'img/martha-s-moscatel-do-douro.jpg', description: 'Martha\'s MOSCATEL do DOURO destaca o perfil aromático típico da Moscatel, com notas florais, frutas maduras e agradável frescor. É um rótulo versátil, indicado para momentos descontraídos e combinações delicadas.', abv: 17.0, pairings: ['Sobremesas', 'Queijos', 'Frutas'] },
    { slug: 'merlot-giaretta', name: 'Merlot Giaretta', category: 'Tinto', price: 36.44, country: 'Brasil', grape: 'Merlot', image: 'img/merlot-giaretta.jpg', description: 'Merlot Giaretta é um tinto macio e frutado, com notas de ameixa e frutas vermelhas, taninos redondos e final agradável.', abv: 12.5, pairings: ['Carnes', 'Massas', 'Pizza'] },
    { slug: 'miolo-selecao-pinot-grigio-riesling', name: 'Miolo Seleção Pinot Grigio & Riesling', category: 'Branco', price: 35.99, country: 'Brasil', grape: 'Pinot Grigio / Riesling', image: 'img/miolo-selecao-pinot-grigio-riesling.jpg', description: 'Miolo Seleção Pinot Grigio & Riesling é um branco leve, fresco e gastronômico, marcado por frutas brancas, toques cítricos e acidez equilibrada.', abv: 11.5, pairings: ['Frutos do Mar', 'Saladas', 'Peixes'] },
    { slug: 'single-vineyard-cabernet-franc', name: 'Single Vineyard Cabernet Franc', category: 'Tinto', price: 77.42, country: 'Brasil', grape: 'Cabernet Franc', image: 'img/single-vineyard-cabernet-franc.jpg', description: 'Single Vineyard Cabernet Franc combina fruta vermelha e negra com notas herbais e especiadas, trazendo estrutura média, frescor e boa vocação gastronômica.', abv: 14.5, pairings: ['Carnes', 'Massas', 'Queijos'] },
    { slug: 'mon-basset-classique-aoc', name: 'Mon Basset Classique Aoc', category: 'Tinto', price: 75.48, country: 'França', grape: 'Blend', image: 'img/mon-basset-classique-aoc.jpg', description: 'Mon Basset Classique Aoc é um tinto de perfil frutado e equilibrado, com boa presença em boca e versatilidade à mesa.', abv: 13.0, pairings: ['Carnes', 'Massas', 'Queijos'] },
    { slug: 'mon-bouquet-de-provence', name: 'Mon Bouquet de Provence', category: 'Rosé', price: 78.5, country: 'França', grape: 'Blend', image: 'img/mon-bouquet-de-provence.jpg', description: 'Mon Bouquet de Provence é um rosé fresco e versátil, com fruta delicada, boa acidez e perfil leve, ideal para momentos descontraídos.', abv: 12.5, pairings: ['Frutos do Mar', 'Saladas', 'Aperitivos'] },
    { slug: 'montana-de-chile-classic-cabernet-sauvignon', name: 'Montaña De Chile Classic Cabernet Sauvignon', category: 'Tinto', price: 44.1, country: 'Argentina', grape: 'Cabernet Sauvignon', image: 'img/montana-de-chile-classic-cabernet-sauvignon.jpg', description: 'Montaña De Chile Classic Cabernet Sauvignon apresenta perfil clássico de Cabernet Sauvignon, com frutas negras, estrutura, taninos presentes e final persistente.', abv: 13.0, pairings: ['Carnes', 'Queijos', 'Massas'] },
    { slug: 'montana-de-chile-classic-chardonnay', name: 'Montaña De Chile Classic Chardonnay', category: 'Branco', price: 44.1, country: 'Argentina', grape: 'Chardonnay', image: 'img/montana-de-chile-classic-chardonnay.jpg', description: 'Montaña De Chile Classic Chardonnay é um branco de perfil frutado e equilibrado, com boa presença de boca e acidez refrescante. Sua versatilidade o torna uma boa companhia para refeições leves.', abv: 13.0, pairings: ['Peixes', 'Frango', 'Massas'] },
    { slug: 'montana-de-chile-classic-merlot', name: 'Montaña De Chile Classic Merlot', category: 'Tinto', price: 44.1, country: 'Argentina', grape: 'Merlot', image: 'img/montana-de-chile-classic-merlot.jpg', description: 'Montaña De Chile Classic Merlot é um tinto macio e frutado, com notas de ameixa e frutas vermelhas, taninos redondos e final agradável.', abv: 13.0, pairings: ['Carnes', 'Massas', 'Pizza'] },
    { slug: 'moscato-giaretta', name: 'Moscato Giaretta', category: 'Branco', price: 36.54, country: 'Brasil', grape: 'Moscatel', image: 'img/moscato-giaretta.jpg', description: 'Moscato Giaretta destaca o perfil aromático típico da Moscatel, com notas florais, frutas maduras e agradável frescor. É um rótulo versátil, indicado para momentos descontraídos e combinações delicadas.', abv: 11.0, pairings: ['Sobremesas', 'Queijos', 'Frutas'] },
    { slug: 'mr-rabbit-pinot-noir', name: 'Mr. Rabbit Pinot Noir', category: 'Tinto', price: 78.3, country: 'França', grape: 'Pinot Noir', image: 'img/mr-rabbit-pinot-noir.jpg', description: 'Mr. Rabbit Pinot Noir mostra o lado elegante e delicado da Pinot Noir, com frutas vermelhas, corpo moderado, taninos macios e boa acidez.', abv: null, pairings: ['Aves', 'Massas', 'Charcutaria'] },
    { slug: 'mr-rabbit-tinto-pays-d-oc-igp-cabernet-sauvignon', name: 'Mr. Rabbit Tinto Pays D’OC IGP Cabernet Sauvignon', category: 'Tinto', price: 69.02, country: 'França', grape: 'Cabernet Sauvignon', image: 'img/mr-rabbit-tinto-pays-d-oc-igp-cabernet-sauvignon.jpg', description: 'Mr. Rabbit Tinto Pays D’OC IGP Cabernet Sauvignon apresenta perfil clássico de Cabernet Sauvignon, com frutas negras, estrutura, taninos presentes e final persistente.', abv: 13.0, pairings: ['Carnes', 'Queijos', 'Massas'] },
    { slug: 'mr-rabbit-tinto-pays-d-oc-igp-syrah', name: 'Mr. Rabbit Tinto Pays D’OC IGP Syrah', category: 'Tinto', price: 69.49, country: 'França', grape: 'Syrah', image: 'img/mr-rabbit-tinto-pays-d-oc-igp-syrah.jpg', description: 'Mr. Rabbit Tinto Pays D’OC IGP Syrah apresenta frutas negras maduras, especiarias e boa presença em boca, com perfil envolvente e gastronômico.', abv: null, pairings: ['Carnes', 'Churrasco', 'Queijos'] },
    { slug: 'mythic-cellars-mountain-petit-verdot', name: 'Mythic Cellars - Mountain - Petit Verdot', category: 'Tinto', price: 93.16, country: 'Argentina', grape: 'Petit Verdot', image: 'img/mythic-cellars-mountain-petit-verdot.jpg', description: 'Mythic Cellars - Mountain - Petit Verdot é um tinto estruturado, de cor intensa, fruta madura e taninos marcantes, ideal para pratos de maior intensidade.', abv: 14.0, pairings: ['Carnes', 'Cordeiro', 'Queijos'] },
    { slug: 'namaqua-merlot', name: 'Namaqua - Merlot', category: 'Tinto', price: 61.79, country: 'África do Sul', grape: 'Merlot', image: 'img/namaqua-merlot.jpg', description: 'Namaqua - Merlot é um tinto macio e frutado, com notas de ameixa e frutas vermelhas, taninos redondos e final agradável.', abv: 13.5, pairings: ['Carnes', 'Massas', 'Pizza'] },
    { slug: 'navalheiro-regional-trasmontano', name: 'Navalheiro Regional Trasmontano', category: 'Tinto', price: 59.72, country: 'Portugal', grape: 'Blend', image: 'img/navalheiro-regional-trasmontano.jpg', description: 'Navalheiro Regional Trasmontano é um tinto de perfil frutado e equilibrado, com boa presença em boca e versatilidade à mesa.', abv: null, pairings: ['Carnes', 'Massas', 'Queijos'] },
    { slug: 'new-roads-blend', name: 'New Roads Blend', category: 'Tinto', price: 33.31, country: 'Argentina', grape: 'Blend', image: 'img/new-roads-blend.jpg', description: 'New Roads Blend é um tinto de perfil frutado e equilibrado, com boa presença em boca e versatilidade à mesa.', abv: 13.2, pairings: ['Carnes', 'Massas', 'Queijos'] },
    { slug: 'no-branding-no-cry', name: 'No Branding No cry', category: 'Tinto', price: 71.75, country: 'Portugal', grape: 'Blend', image: 'img/no-branding-no-cry.jpg', description: 'No Branding No cry é um tinto de perfil frutado e equilibrado, com boa presença em boca e versatilidade à mesa.', abv: 13.0, pairings: ['Carnes', 'Massas', 'Queijos'] },
    { slug: 'nobili-d-italia-montepulciano-d-abruzzo', name: 'Nobili D\'Italia Montepulciano D\' Abruzzo', category: 'Branco', price: 67.62, country: 'Itália', grape: 'Montepulciano', image: 'img/nobili-d-italia-montepulciano-d-abruzzo.jpg', description: 'Nobili D\'Italia Montepulciano D\' Abruzzo expressa um estilo italiano gastronômico, com fruta madura, especiarias, boa acidez e estrutura equilibrada.', abv: 13.0, pairings: ['Massas', 'Pizza', 'Carnes'] },
    { slug: 'nobili-d-italia-trebbiano-d-abruzzo', name: 'Nobili D\'italia Trebbiano D\' Abruzzo', category: 'Branco', price: 65.63, country: 'Itália', grape: 'Trebbiano', image: 'img/nobili-d-italia-trebbiano-d-abruzzo.jpg', description: 'Nobili D\'italia Trebbiano D\' Abruzzo é um branco leve, fresco e gastronômico, marcado por frutas brancas, toques cítricos e acidez equilibrada.', abv: null, pairings: ['Frutos do Mar', 'Saladas', 'Peixes'] },
    { slug: 'paso-de-los-andes-reserva-pinot-noir', name: 'Paso de Los Andes Reserva Pinot Noir', category: 'Tinto', price: 51.8, country: 'Chile', grape: 'Pinot Noir', image: 'img/paso-de-los-andes-reserva-pinot-noir.jpg', description: 'Paso de Los Andes Reserva Pinot Noir mostra o lado elegante e delicado da Pinot Noir, com frutas vermelhas, corpo moderado, taninos macios e boa acidez.', abv: 13.5, pairings: ['Aves', 'Massas', 'Charcutaria'] },
    { slug: 'pao-de-los-andes-cabernet-sauvignon', name: 'Pao de Los Andes Cabernet Sauvignon', category: 'Tinto', price: 58.87, country: 'Chile', grape: 'Cabernet Sauvignon', image: 'img/pao-de-los-andes-cabernet-sauvignon.jpg', description: 'Pao de Los Andes Cabernet Sauvignon apresenta perfil clássico de Cabernet Sauvignon, com frutas negras, estrutura, taninos presentes e final persistente.', abv: 13.0, pairings: ['Carnes', 'Queijos', 'Massas'] },
    { slug: 'passo-de-los-andes-carmenere', name: 'Passo de Los Andes Carménère', category: 'Tinto', price: 58.87, country: 'Chile', grape: 'Carménère', image: 'img/passo-de-los-andes-carmenere.jpg', description: 'Passo de Los Andes Carménère é um tinto de perfil frutado e equilibrado, com boa presença em boca e versatilidade à mesa.', abv: 13.0, pairings: ['Carnes', 'Massas', 'Queijos'] },
    { slug: 'passaro-da-lua-blend', name: 'Pássaro da Lua Blend', category: 'Tinto', price: 159.5, country: 'Brasil', grape: 'Blend', image: 'img/passaro-da-lua-blend.jpg', description: 'Pássaro da Lua Blend é um tinto de perfil frutado e equilibrado, com boa presença em boca e versatilidade à mesa.', abv: 12.7, pairings: ['Carnes', 'Massas', 'Queijos'] },
    { slug: 'passaro-da-lua-tannat', name: 'Pássaro da Lua Tannat', category: 'Tinto', price: 159.5, country: 'Brasil', grape: 'Tannat', image: 'img/passaro-da-lua-tannat.jpg', description: 'Pássaro da Lua Tannat é um tinto estruturado, de cor intensa, fruta madura e taninos marcantes, ideal para pratos de maior intensidade.', abv: 12.5, pairings: ['Carnes', 'Cordeiro', 'Queijos'] },
    { slug: 'passo-de-los-andes-moskato', name: 'Passo de Los Andes Moskato', category: 'Tinto', price: 36.8, country: 'Chile', grape: 'Moscatel', image: 'img/passo-de-los-andes-moskato.jpg', description: 'Passo de Los Andes Moskato destaca o perfil aromático típico da Moscatel, com notas florais, frutas maduras e agradável frescor. É um rótulo versátil, indicado para momentos descontraídos e combinações delicadas.', abv: null, pairings: ['Sobremesas', 'Queijos', 'Frutas'] },
    { slug: 'pescada-blend-verde', name: 'Pescada Blend Verde', category: 'Branco', price: 83.77, country: 'Portugal', grape: 'Blend', image: 'img/pescada-blend-verde.jpg', description: 'Pescada Blend Verde é um branco fresco e equilibrado, com perfil frutado e boa acidez, pensado para consumo leve e descontraído.', abv: null, pairings: ['Peixes', 'Frutos do Mar', 'Saladas'] },
    { slug: 'plexus-espumante-branco', name: 'Plexus Espumante Branco', category: 'Branco', price: 43.93, country: 'Portugal', grape: 'Blend', image: 'img/plexus-espumante-branco.jpg', description: 'Plexus Espumante Branco é um branco fresco e equilibrado, com perfil frutado e boa acidez, pensado para consumo leve e descontraído.', abv: null, pairings: ['Peixes', 'Frutos do Mar', 'Saladas'] },
    { slug: 'plexus-espumante-rose', name: 'Plexus Espumante Rosé', category: 'Rosé', price: 43.93, country: 'Portugal', grape: 'Blend', image: 'img/plexus-espumante-rose.jpg', description: 'Plexus Espumante Rosé é um tinto de perfil frutado e equilibrado, com boa presença em boca e versatilidade à mesa.', abv: 9.5, pairings: ['Carnes', 'Massas', 'Queijos'] },
    { slug: 'pode-ser', name: 'Pode Ser', category: 'Tinto', price: 50.87, country: 'Portugal', grape: 'Blend', image: 'img/pode-ser.jpg', description: 'Pode Ser é um tinto de perfil frutado e equilibrado, com boa presença em boca e versatilidade à mesa.', abv: 13.0, pairings: ['Carnes', 'Massas', 'Queijos'] },
    { slug: 'porta-6', name: 'Porta 6', category: 'Tinto', price: 57.1, country: 'Portugal', grape: 'Blend', image: 'img/porta-6.jpg', description: 'Porta 6 é um tinto de perfil frutado e equilibrado, com boa presença em boca e versatilidade à mesa.', abv: 13.5, pairings: ['Carnes', 'Massas', 'Queijos'] },
    { slug: 'porta-6-reserva', name: 'Porta 6 Reserva', category: 'Tinto', price: 86.42, country: 'Portugal', grape: 'Blend', image: 'img/porta-6-reserva.jpg', description: 'Porta 6 Reserva é um tinto de perfil frutado e equilibrado, com boa presença em boca e versatilidade à mesa.', abv: 14.0, pairings: ['Carnes', 'Massas', 'Queijos'] },
    { slug: 'profugo-malbec', name: 'Profugo Malbec', category: 'Tinto', price: 50.98, country: 'Argentina', grape: 'Malbec', image: 'img/profugo-malbec.jpg', description: 'Profugo Malbec entrega frutas maduras, boa intensidade e taninos macios, com um perfil envolvente e fácil de harmonizar.', abv: 12.8, pairings: ['Carnes', 'Hambúrguer', 'Massas'] },
    { slug: 'profugo-sauvignon-blanc', name: 'Profugo Sauvignon Blanc', category: 'Branco', price: 50.98, country: 'Argentina', grape: 'Sauvignon Blanc', image: 'img/profugo-sauvignon-blanc.jpg', description: 'Profugo Sauvignon Blanc apresenta perfil fresco e aromático, com notas cítricas, frutas de polpa branca e boa vivacidade. Um branco leve e refrescante, ótimo para dias quentes e pratos delicados.', abv: 12.5, pairings: ['Frutos do Mar', 'Peixes', 'Saladas'] },
    { slug: 'rola-colheita', name: 'Rola Colheita', category: 'Tinto', price: 122.08, country: 'Portugal', grape: 'Blend', image: 'img/rola-colheita.jpg', description: 'Rola Colheita é um tinto de perfil frutado e equilibrado, com boa presença em boca e versatilidade à mesa.', abv: null, pairings: ['Carnes', 'Massas', 'Queijos'] },
    { slug: 'rosso-toscana-igt-rifugio-del-vescovo', name: 'Rosso Toscana Igt Rifugio Del Vescovo', category: 'Tinto', price: 95.65, country: 'Itália', grape: 'Blend', image: 'img/rosso-toscana-igt-rifugio-del-vescovo.jpg', description: 'Rosso Toscana Igt Rifugio Del Vescovo é um tinto de perfil frutado e equilibrado, com boa presença em boca e versatilidade à mesa.', abv: null, pairings: ['Carnes', 'Massas', 'Queijos'] },
    { slug: 'sierra-batuco-reserva-cabernet-sauvignon', name: 'Sierra Batuco Reserva Cabernet Sauvignon', category: 'Tinto', price: 57.87, country: 'Chile', grape: 'Cabernet Sauvignon', image: 'img/sierra-batuco-reserva-cabernet-sauvignon.jpg', description: 'Sierra Batuco Reserva Cabernet Sauvignon apresenta perfil clássico de Cabernet Sauvignon, com frutas negras, estrutura, taninos presentes e final persistente.', abv: 13.9, pairings: ['Carnes', 'Queijos', 'Massas'] },
    { slug: 'sierra-batuco-reserva-pinot-noir', name: 'Sierra Batuco Reserva Pinot Noir', category: 'Tinto', price: 57.87, country: 'Chile', grape: 'Pinot Noir', image: 'img/sierra-batuco-reserva-pinot-noir.jpg', description: 'Sierra Batuco Reserva Pinot Noir mostra o lado elegante e delicado da Pinot Noir, com frutas vermelhas, corpo moderado, taninos macios e boa acidez.', abv: 13.9, pairings: ['Aves', 'Massas', 'Charcutaria'] },
    { slug: 'single-vineyard-pinot-noir', name: 'Single Vineyard Pinot Noir', category: 'Tinto', price: 67.17, country: 'Brasil', grape: 'Pinot Noir', image: 'img/single-vineyard-pinot-noir.jpg', description: 'Single Vineyard Pinot Noir mostra o lado elegante e delicado da Pinot Noir, com frutas vermelhas, corpo moderado, taninos macios e boa acidez.', abv: 13.5, pairings: ['Aves', 'Massas', 'Charcutaria'] },
    { slug: 'single-vineyard-touriga-nacional', name: 'Single Vineyard Touriga Nacional', category: 'Tinto', price: 67.17, country: 'Brasil', grape: 'Touriga Nacional', image: 'img/single-vineyard-touriga-nacional.jpg', description: 'Single Vineyard Touriga Nacional é um tinto estruturado, de cor intensa, fruta madura e taninos marcantes, ideal para pratos de maior intensidade.', abv: 13.5, pairings: ['Carnes', 'Cordeiro', 'Queijos'] },
    { slug: 'stormhoek-pinotage', name: 'Stormhoek Pinotage', category: 'Tinto', price: 60.86, country: 'África do Sul', grape: 'Pinotage', image: 'img/stormhoek-pinotage.jpg', description: 'Stormhoek Pinotage apresenta frutas negras maduras, especiarias e boa presença em boca, com perfil envolvente e gastronômico.', abv: 13.0, pairings: ['Carnes', 'Churrasco', 'Queijos'] },
    { slug: 'sutter-home', name: 'Sutter Home', category: 'Tinto', price: 89.09, country: 'EUA', grape: 'Cabernet Sauvignon', image: 'img/sutter-home.jpg', description: 'Sutter Home apresenta perfil clássico de Cabernet Sauvignon, com frutas negras, estrutura, taninos presentes e final persistente.', abv: 12.9, pairings: ['Carnes', 'Queijos', 'Massas'] },
    { slug: 'tannat-giaretta', name: 'Tannat Giaretta', category: 'Tinto', price: 57.74, country: 'Brasil', grape: 'Tannat', image: 'img/tannat-giaretta.jpg', description: 'Tannat Giaretta é um tinto estruturado, de cor intensa, fruta madura e taninos marcantes, ideal para pratos de maior intensidade.', abv: 12.8, pairings: ['Carnes', 'Cordeiro', 'Queijos'] },
    { slug: 'terramater-vineyard-pinot-noir-reserve', name: 'Terramater Vineyard Pinot Noir Reserve', category: 'Tinto', price: 94.86, country: 'Chile', grape: 'Pinot Noir', image: 'img/terramater-vineyard-pinot-noir-reserve.jpg', description: 'Terramater Vineyard Pinot Noir Reserve mostra o lado elegante e delicado da Pinot Noir, com frutas vermelhas, corpo moderado, taninos macios e boa acidez.', abv: 13.8, pairings: ['Aves', 'Massas', 'Charcutaria'] },
    { slug: 'torre-romanica-primitivo', name: 'Torre Romanica Primitivo', category: 'Tinto', price: 69.41, country: 'Itália', grape: 'Primitivo', image: 'img/torre-romanica-primitivo.jpg', description: 'Torre Romanica Primitivo expressa um estilo italiano gastronômico, com fruta madura, especiarias, boa acidez e estrutura equilibrada.', abv: 13.0, pairings: ['Massas', 'Pizza', 'Carnes'] },
    { slug: 'torre-romanica-sangiovese', name: 'Torre Romanica Sangiovese', category: 'Tinto', price: 51.48, country: 'Itália', grape: 'Sangiovese', image: 'img/torre-romanica-sangiovese.jpg', description: 'Torre Romanica Sangiovese expressa um estilo italiano gastronômico, com fruta madura, especiarias, boa acidez e estrutura equilibrada.', abv: 12.5, pairings: ['Massas', 'Pizza', 'Carnes'] },
    { slug: 'vezzani-montepulciano', name: 'Vezzani Montepulciano', category: 'Rosé', price: 91.32, country: 'Itália', grape: 'Montepulciano', image: 'img/vezzani-montepulciano.jpg', description: 'Vezzani Montepulciano expressa um estilo italiano gastronômico, com fruta madura, especiarias, boa acidez e estrutura equilibrada.', abv: null, pairings: ['Massas', 'Pizza', 'Carnes'] },
    { slug: 'vezzani-negroamaro-rosato', name: 'Vezzani Negroamaro Rosato', category: 'Rosé', price: 88.55, country: 'Itália', grape: 'Negroamaro', image: 'img/vezzani-negroamaro-rosato.jpg', description: 'Vezzani Negroamaro Rosato expressa um estilo italiano gastronômico, com fruta madura, especiarias, boa acidez e estrutura equilibrada.', abv: 12.5, pairings: ['Massas', 'Pizza', 'Carnes'] },
    { slug: 'vezzani-nero-d-avola', name: 'Vezzani Nero D\'Avola', category: 'Tinto', price: 89.85, country: 'Itália', grape: 'Nero D\'Avola', image: 'img/vezzani-nero-d-avola.jpg', description: 'Vezzani Nero D\'Avola expressa um estilo italiano gastronômico, com fruta madura, especiarias, boa acidez e estrutura equilibrada.', abv: 13.0, pairings: ['Massas', 'Pizza', 'Carnes'] },
    { slug: 'vezzani-nero-di-troia', name: 'Vezzani Nero di Troia', category: 'Tinto', price: 91.71, country: 'Itália', grape: 'Nero Di Troia', image: 'img/vezzani-nero-di-troia.jpg', description: 'Vezzani Nero di Troia expressa um estilo italiano gastronômico, com fruta madura, especiarias, boa acidez e estrutura equilibrada.', abv: 14.0, pairings: ['Massas', 'Pizza', 'Carnes'] },
    { slug: 'vezzani-trebbiano', name: 'Vezzani Trebbiano', category: 'Branco', price: 66.12, country: 'Itália', grape: 'Trebbiano', image: 'img/vezzani-trebbiano.jpg', description: 'Vezzani Trebbiano é um branco leve, fresco e gastronômico, marcado por frutas brancas, toques cítricos e acidez equilibrada.', abv: null, pairings: ['Frutos do Mar', 'Saladas', 'Peixes'] },
    { slug: 'vinas-del-tango-cabernet-sauvignon', name: 'Viñas Del Tango Cabernet Sauvignon', category: 'Tinto', price: 59.36, country: 'Argentina', grape: 'Cabernet Sauvignon', image: 'img/vinas-del-tango-cabernet-sauvignon.jpg', description: 'Viñas Del Tango Cabernet Sauvignon apresenta perfil clássico de Cabernet Sauvignon, com frutas negras, estrutura, taninos presentes e final persistente.', abv: 13.2, pairings: ['Carnes', 'Queijos', 'Massas'] },
    { slug: 'vinas-del-tango-selection-cabernet-franc', name: 'Viñas Del Tango Selection Cabernet Franc', category: 'Tinto', price: 47.49, country: 'Argentina', grape: 'Cabernet Franc', image: 'img/vinas-del-tango-selection-cabernet-franc.jpg', description: 'Viñas Del Tango Selection Cabernet Franc combina fruta vermelha e negra com notas herbais e especiadas, trazendo estrutura média, frescor e boa vocação gastronômica.', abv: 13.0, pairings: ['Carnes', 'Massas', 'Queijos'] },
    { slug: 'vinas-del-tango-selection-malbec', name: 'Viñas Del Tango Selection Malbec', category: 'Tinto', price: 49.9, country: 'Argentina', grape: 'Malbec', image: 'img/vinas-del-tango-selection-malbec.jpg', description: 'Viñas Del Tango Selection Malbec entrega frutas maduras, boa intensidade e taninos macios, com um perfil envolvente e fácil de harmonizar.', abv: 13.5, pairings: ['Carnes', 'Hambúrguer', 'Massas'] },
    { slug: 'miolo-wild-ganmay', name: 'Miolo Wild Ganmay', category: 'Tinto', price: 62.94, country: 'Brasil', grape: 'Gamay', image: 'img/miolo-wild-ganmay.jpg', description: 'Miolo Wild Ganmay é um tinto de perfil frutado e equilibrado, com boa presença em boca e versatilidade à mesa.', abv: 14.0, pairings: ['Carnes', 'Massas', 'Queijos'] },
    { slug: 'winemaker-secret-branco', name: 'Winemaker Secret Branco', category: 'Branco', price: 63.43, country: 'Chile', grape: 'Blend', image: 'img/winemaker-secret-branco.jpg', description: 'Winemaker Secret Branco é um branco fresco e equilibrado, com perfil frutado e boa acidez, pensado para consumo leve e descontraído.', abv: null, pairings: ['Peixes', 'Frutos do Mar', 'Saladas'] },
    { slug: 'winemaker-secret-rose', name: 'Winemaker Secret Rosé', category: 'Rosé', price: 63.43, country: 'Chile', grape: 'Blend', image: 'img/winemaker-secret-rose.jpg', description: 'Winemaker Secret Rosé é um rosé fresco e versátil, com fruta delicada, boa acidez e perfil leve, ideal para momentos descontraídos.', abv: null, pairings: ['Frutos do Mar', 'Saladas', 'Aperitivos'] },
    { slug: 'yali-wild-swan-sauvignon-blanc', name: 'Yali - Wild Swan Sauvignon Blanc', category: 'Branco', price: 69.88, country: 'Chile', grape: 'Sauvignon Blanc', image: 'img/yali-wild-swan-sauvignon-blanc.jpg', description: 'Yali - Wild Swan Sauvignon Blanc apresenta perfil fresco e aromático, com notas cítricas, frutas de polpa branca e boa vivacidade. Um branco leve e refrescante, ótimo para dias quentes e pratos delicados.', abv: 12.5, pairings: ['Frutos do Mar', 'Peixes', 'Saladas'] },
    { slug: 'romanica-pinot-grigio', name: 'Romanica Pinot Grigio', category: 'Branco', price: 65.78, country: 'Itália', grape: 'Pinot Grigio', image: 'img/romanica-pinot-grigio.jpg', description: 'Romanica Pinot Grigio é um branco leve, fresco e gastronômico, marcado por frutas brancas, toques cítricos e acidez equilibrada.', abv: null, pairings: ['Frutos do Mar', 'Saladas', 'Peixes'] },
    { slug: 'stormhoek-shiraz-pure', name: 'Stormhoek Shiraz Pure', category: 'Tinto', price: 69.7, country: 'África do Sul', grape: 'Syrah', image: 'img/stormhoek-shiraz-pure.jpg', description: 'Stormhoek Shiraz Pure apresenta frutas negras maduras, especiarias e boa presença em boca, com perfil envolvente e gastronômico.', abv: 0.5, pairings: ['Carnes', 'Churrasco', 'Queijos'] },
    { slug: 'marthas-porto-rose', name: 'Marthas Porto Rosé', category: 'Rosé', price: 117.99, country: 'Portugal', grape: 'Blend', image: 'img/marthas-porto-rose.jpg', description: 'Marthas Porto Rosé é um tinto de perfil frutado e equilibrado, com boa presença em boca e versatilidade à mesa.', abv: 19.0, pairings: ['Carnes', 'Massas', 'Queijos'] },
    { slug: 'paso-de-los-andes-reserva-tinto', name: 'Paso de Los Andes Reserva Tinto', category: 'Tinto', price: 50.62, country: 'Chile', grape: 'Blend', image: 'img/paso-de-los-andes-reserva-tinto.jpg', description: 'Paso de Los Andes Reserva Tinto é um tinto de perfil frutado e equilibrado, com boa presença em boca e versatilidade à mesa.', abv: null, pairings: ['Carnes', 'Massas', 'Queijos'] },
    { slug: 'isla-negra-carmenere', name: 'Isla Negra Carménère', category: 'Tinto', price: 34.99, country: 'Chile', grape: 'Carménère', image: 'img/isla-negra-carmenere.jpg', description: 'O Isla Negra Carménère é aquele tinto chileno perfeito para quem busca um vinho macio, fácil de beber e pronto para acompanhar bons momentos à mesa. Combina muito bem com jantares descontraídos, massas ao molho vermelho, carnes grelhadas, hambúrguer artesanal, pizzas e pratos com temperos suaves.', abv: 12.0, pairings: ['Carnes', 'Lanches', 'Salgados'] },
  ];

  const CATEGORIES = [...new Set(MENU.map((w) => w.category))];

  function findBySlug(slug) {
    return MENU.find((w) => w.slug === slug);
  }

  // Remove acentos para a busca não depender de o cliente digitar exatamente
  // (ex.: "torrontes" precisa achar "Torrontés").
  function normalizeText(value) {
    return String(value == null ? '' : value)
      .normalize('NFD')
      .replace(/[̀-ͯ]/g, '')
      .toLowerCase();
  }

  function searchByName(query) {
    const q = normalizeText(query).trim();
    if (!q) return [];
    return MENU.filter((w) => normalizeText(w.name).indexOf(q) !== -1);
  }

  function suggestPairings(slug, count) {
    const target = findBySlug(slug);
    if (!target) return [];
    const others = MENU.filter((w) => w.slug !== slug);
    const scored = others.map((w) => {
      let score = 0;
      if (w.country === target.country) score += 2;
      if (w.grape === target.grape) score += 1;
      return { wine: w, score };
    });
    scored.sort((a, b) => b.score - a.score);
    return scored.slice(0, count).map((s) => s.wine);
  }

  // Ícone por categoria de harmonização (Catalog.MENU[].pairings). Cobre as
  // categorias que aparecem na planilha de produtos; categoria nova e ainda
  // não mapeada cai no ícone padrão de taça.
  const PAIRING_ICONS = {
    'Aperitivos': '🥂',
    'Aves': '🍗',
    'Bacalhau': '🐟',
    'Bolos': '🍰',
    'Carnes': '🥩',
    'Ceviche': '🍤',
    'Charcutaria': '🧀',
    'Churrasco': '🔥',
    'Cordeiro': '🐑',
    'Embutidos': '🌭',
    'Ensopados': '🍲',
    'Frango': '🍗',
    'Frutas': '🍇',
    'Frutos do Mar': '🦐',
    'Hambúrguer': '🍔',
    'Lanches': '🥪',
    'Massas': '🍝',
    'Mouse': '🍮',
    'Ossobuco': '🍲',
    'Peixes': '🐟',
    'Pizza': '🍕',
    'Queijos': '🧀',
    'Saladas': '🥗',
    'Salgados': '🥟',
    'Sobremesas': '🍰'
  };
  const DEFAULT_PAIRING_ICON = '🍷';

  function pairingIcon(category) {
    return PAIRING_ICONS[category] || DEFAULT_PAIRING_ICON;
  }

  return { MENU, CATEGORIES, findBySlug, suggestPairings, searchByName, pairingIcon };
});
