import { Wine } from './types';

export const INITIAL_WINES: Omit<Wine, 'description'>[] = [
  {
    id: 1,
    name: '3 Autores',
    type: 'Tinto',
    region: 'Portugal',
    price: 51.36,
    imageUrl: 'https://picsum.photos/seed/3-autores/400/600',
  },
  {
    id: 2,
    name: 'ADEGA GRANDE MESA - ROSÉ',
    type: 'Rosé',
    region: 'Portugal',
    price: 38.83,
    imageUrl: 'https://picsum.photos/seed/adega-grande-mesa-rose/400/600',
  },
  {
    id: 3,
    name: 'Amo-te tinto',
    type: 'Tinto',
    region: 'Portugal',
    price: 53.65,
    imageUrl: 'https://picsum.photos/seed/amo-te-tinto/400/600',
  },
  {
    id: 4,
    name: 'Ancelotta Giaretta',
    type: 'Tinto',
    region: 'Serra Gaúcha, Brasil',
    price: 31.78,
    imageUrl: 'https://picsum.photos/seed/ancelotta-giaretta/400/600',
  },
  {
    id: 5,
    name: 'Arinarmoa Giaretta',
    type: 'Tinto',
    region: 'Serra Gaúcha, Brasil',
    price: 60.72,
    imageUrl: 'https://picsum.photos/seed/arinarmoa-giaretta/400/600',
  },
  {
    id: 6,
    name: 'Artola',
    type: 'Tinto',
    region: 'Espanha',
    price: 36.97,
    imageUrl: 'https://picsum.photos/seed/artola/400/600',
  },
  {
    id: 7,
    name: 'Artolas Branco',
    type: 'Branco',
    region: 'Portugal',
    price: 34.88,
    imageUrl: 'https://picsum.photos/seed/artolas-branco/400/600',
  },
  {
    id: 8,
    name: 'Bianco Toscana Igt Rifugio Del Vescovo',
    type: 'Branco',
    region: 'Toscana, Itália',
    price: 89.61,
    imageUrl: 'https://picsum.photos/seed/bianco-toscana-igt/400/600',
  },
  {
    id: 9,
    name: 'Boa Noite Lisboa',
    type: 'Tinto',
    region: 'Lisboa, Portugal',
    price: 48.97,
    imageUrl: 'https://picsum.photos/seed/boa-noite-lisboa/400/600',
  },
  {
    id: 10,
    name: 'BODEGA PRIVADA MALBEC',
    type: 'Tinto',
    region: 'Mendoza, Argentina',
    price: 53.23,
    imageUrl: 'https://picsum.photos/seed/bodega-privada-malbec/400/600',
  },
  {
    id: 11,
    name: 'Bodega Torrontés',
    type: 'Branco',
    region: 'Argentina',
    price: 39.9,
    imageUrl: 'https://picsum.photos/seed/bodega-torrontes/400/600',
  },
  {
    id: 12,
    name: 'Buenardo Malbec Vinho Orgânico',
    type: 'Tinto',
    region: 'Mendoza, Argentina',
    price: 69.12,
    imageUrl: 'https://picsum.photos/seed/buenardo-malbec/400/600',
  },
  {
    id: 13,
    name: 'Cà Montebello BARBERA',
    type: 'Tinto',
    region: 'Piemonte, Itália',
    price: 80.51,
    imageUrl: 'https://picsum.photos/seed/ca-montebello-barbera/400/600',
  },
  {
    id: 14,
    name: 'Cà Montebello Pinot Nero',
    type: 'Tinto',
    region: 'Piemonte, Itália',
    price: 73.96,
    imageUrl: 'https://picsum.photos/seed/ca-montebello-pinot-nero/400/600',
  },
  {
    id: 15,
    name: 'Calvet Varietals Merlot',
    type: 'Tinto',
    region: 'França',
    price: 61.23,
    imageUrl: 'https://picsum.photos/seed/calvet-merlot/400/600',
  },
  {
    id: 16,
    name: 'Castas Diferenciadas Cabernet Franc',
    type: 'Tinto',
    region: 'Brasil',
    price: 59.8,
    imageUrl: 'https://picsum.photos/seed/castas-cabernet-franc/400/600',
  },
  {
    id: 17,
    name: 'CASTAS DIFERENCIADAS GEWURZTRAMINER',
    type: 'Branco',
    region: 'Brasil',
    price: 43.94,
    imageUrl: 'https://picsum.photos/seed/castas-gewurztraminer/400/600',
  },
  {
    id: 18,
    name: 'Cavic Malbec',
    type: 'Tinto',
    region: 'Argentina',
    price: 41.57,
    imageUrl: 'https://picsum.photos/seed/cavic-malbec/400/600',
  },
  {
    id: 19,
    name: 'Chardonnay Giaretta',
    type: 'Branco',
    region: 'Serra Gaúcha, Brasil',
    price: 33.65,
    imageUrl: 'https://picsum.photos/seed/chardonnay-giaretta/400/600',
  },
  {
    id: 20,
    name: 'Château Bel Enclos',
    type: 'Tinto',
    region: 'Bordeaux, França',
    price: 52.0,
    imageUrl: 'https://picsum.photos/seed/chateau-bel-enclos/400/600',
  },
  {
    id: 21,
    name: "Château Maine D'Arman - Côtes de Bourg AOC",
    type: 'Tinto',
    region: 'Bordeaux, França',
    price: 108.18,
    imageUrl: 'https://picsum.photos/seed/chateau-maine-darman/400/600',
  },
  {
    id: 22,
    name: 'Chavarri - Larchago - Rioja DOCa',
    type: 'Tinto',
    region: 'Rioja, Espanha',
    price: 107.97,
    imageUrl: 'https://picsum.photos/seed/chavarri-larchago-rioja/400/600',
  },
  {
    id: 23,
    name: 'Chianti Rifugio Del Vescovo',
    type: 'Tinto',
    region: 'Toscana, Itália',
    price: 80.37,
    imageUrl: 'https://picsum.photos/seed/chianti-rifugio/400/600',
  },
  {
    id: 24,
    name: 'Coragem Tinto',
    type: 'Tinto',
    region: 'Portugal',
    price: 38.27,
    imageUrl: 'https://picsum.photos/seed/coragem-tinto/400/600',
  },
  {
    id: 25,
    name: 'Corinto Carmenere – 2021',
    type: 'Tinto',
    region: 'Chile',
    price: 46.87,
    imageUrl: 'https://picsum.photos/seed/corinto-carmenere/400/600',
  },
  {
    id: 26,
    name: 'Corinto Reserva Cabernet Sauvignon – 2018',
    type: 'Tinto',
    region: 'Chile',
    price: 52.65,
    imageUrl: 'https://picsum.photos/seed/corinto-reserva-cabernet/400/600',
  },
  {
    id: 27,
    name: 'Côtes Du Rhone Chatelain Valmont',
    type: 'Tinto',
    region: 'Rhône, França',
    price: 53.34,
    imageUrl: 'https://picsum.photos/seed/cotes-du-rhone-valmont/400/600',
  },
  {
    id: 28,
    name: 'CRUZEIRO DOS ARCOS VINHO VERDE',
    type: 'Branco',
    region: 'Portugal',
    price: 52.48,
    imageUrl: 'https://picsum.photos/seed/cruzeiro-dos-arcos/400/600',
  },
  {
    id: 29,
    name: 'Da Pipa Frisante Rosé',
    type: 'Espumante',
    region: 'Portugal',
    price: 27.41,
    imageUrl: 'https://picsum.photos/seed/da-pipa-frisante-rose/400/600',
  },
  {
    id: 30,
    name: 'Deinhard Green Label Riesling',
    type: 'Branco',
    region: 'Alemanha',
    price: 76.34,
    imageUrl: 'https://picsum.photos/seed/deinhard-riesling/400/600',
  },
  {
    id: 31,
    name: 'Emersão - Merlot',
    type: 'Tinto',
    region: 'Brasil',
    price: 107.51,
    imageUrl: 'https://picsum.photos/seed/emersao-merlot/400/600',
  },
  {
    id: 32,
    name: 'Emersão - Syrah',
    type: 'Tinto',
    region: 'Brasil',
    price: 122.4,
    imageUrl: 'https://picsum.photos/seed/emersao-syrah/400/600',
  },
  {
    id: 33,
    name: 'Emersão Blend',
    type: 'Tinto',
    region: 'Brasil',
    price: 123.22,
    imageUrl: 'https://picsum.photos/seed/emersao-blend/400/600',
  },
  {
    id: 34,
    name: 'Excelso Reserva Cabernet Sauvignon',
    type: 'Tinto',
    region: 'Chile',
    price: 76.79,
    imageUrl: 'https://picsum.photos/seed/excelso-reserva-cabernet/400/600',
  },
  {
    id: 35,
    name: 'Flor de Lisboa Tinto',
    type: 'Tinto',
    region: 'Lisboa, Portugal',
    price: 30.87,
    imageUrl: 'https://picsum.photos/seed/flor-de-lisboa-tinto/400/600',
  },
  {
    id: 36,
    name: 'Fonte da Perdiz Branco D.O.C.',
    type: 'Branco',
    region: 'Portugal',
    price: 44.56,
    imageUrl: 'https://picsum.photos/seed/fonte-da-perdiz-branco/400/600',
  },
  {
    id: 37,
    name: 'Frisante Almadén Moscatel Rosé',
    type: 'Espumante',
    region: 'Serra Gaúcha, Brasil',
    price: 24.49,
    imageUrl: 'https://picsum.photos/seed/almaden-moscatel-rose/400/600',
  },
  {
    id: 38,
    name: 'Herdade do Gamito tinto Alicante Bouschet',
    type: 'Tinto',
    region: 'Alentejo, Portugal',
    price: 90.94,
    imageUrl: 'https://picsum.photos/seed/herdade-gamito-alicante/400/600',
  },
  {
    id: 39,
    name: 'Herdade Grande Origens',
    type: 'Tinto',
    region: 'Alentejo, Portugal',
    price: 51.3,
    imageUrl: 'https://picsum.photos/seed/herdade-grande-origens/400/600',
  },
  {
    id: 40,
    name: 'Iciottoli Cabernet Sauvignon',
    type: 'Tinto',
    region: 'Itália',
    price: 86.39,
    imageUrl: 'https://picsum.photos/seed/iciottoli-cabernet/400/600',
  },
  {
    id: 41,
    name: 'Ique Vegano',
    type: 'Tinto',
    region: 'Argentina',
    price: 44.8,
    imageUrl: 'https://picsum.photos/seed/ique-vegano/400/600',
  },
  {
    id: 42,
    name: 'Isla Negra Cabernet Sauvignon',
    type: 'Tinto',
    region: 'Vale Central, Chile',
    price: 28.47,
    imageUrl: 'https://picsum.photos/seed/isla-negra-cabernet/400/600',
  },
  {
    id: 43,
    name: 'Isla Negra Merlot',
    type: 'Tinto',
    region: 'Vale Central, Chile',
    price: 28.47,
    imageUrl: 'https://picsum.photos/seed/isla-negra-merlot/400/600',
  },
  {
    id: 44,
    name: 'Júlia Florista',
    type: 'Tinto',
    region: 'Lisboa, Portugal',
    price: 36.31,
    imageUrl: 'https://picsum.photos/seed/julia-florista/400/600',
  },
  {
    id: 45,
    name: 'Júlia Florista RESERVA',
    type: 'Tinto',
    region: 'Lisboa, Portugal',
    price: 53.1,
    imageUrl: 'https://picsum.photos/seed/julia-florista-reserva/400/600',
  },
  {
    id: 46,
    name: 'La Barbacoa Garnacha',
    type: 'Tinto',
    region: 'Espanha',
    price: 57.83,
    imageUrl: 'https://picsum.photos/seed/la-barbacoa-garnacha/400/600',
  },
  {
    id: 47,
    name: 'La Treille De Candale',
    type: 'Tinto',
    region: 'Bordeaux, França',
    price: 46.48,
    imageUrl: 'https://picsum.photos/seed/la-treille-de-candale/400/600',
  },
  {
    id: 48,
    name: 'Lacase Carménére',
    type: 'Tinto',
    region: 'Chile',
    price: 28.13,
    imageUrl: 'https://picsum.photos/seed/lacase-carmenere-1/400/600',
  },
  {
    id: 49,
    name: 'Lacase Carménére',
    type: 'Tinto',
    region: 'Chile',
    price: 39.9,
    imageUrl: 'https://picsum.photos/seed/lacase-carmenere-2/400/600',
  },
  {
    id: 50,
    name: 'Late Harverst Miolo',
    type: 'Branco',
    region: 'Vale dos Vinhedos, Brasil',
    price: 56.3,
    imageUrl: 'https://picsum.photos/seed/late-harvest-miolo/400/600',
  },
  {
    id: 51,
    name: 'Marselan Giaretta',
    type: 'Tinto',
    region: 'Serra Gaúcha, Brasil',
    price: 45.29,
    imageUrl: 'https://picsum.photos/seed/marselan-giaretta/400/600',
  },
  {
    id: 52,
    name: "Martha's MOSCATEL do DOURO",
    type: 'Branco',
    region: 'Douro, Portugal',
    price: 54.69,
    imageUrl: 'https://picsum.photos/seed/marthas-moscatel-douro/400/600',
  },
  {
    id: 53,
    name: "Martha's PORTO tinto TAWNY",
    type: 'Tinto',
    region: 'Douro, Portugal',
    price: 71.47,
    imageUrl: 'https://picsum.photos/seed/marthas-porto-tawny/400/600',
  },
  {
    id: 54,
    name: 'Merlot Giaretta',
    type: 'Tinto',
    region: 'Serra Gaúcha, Brasil',
    price: 30.16,
    imageUrl: 'https://picsum.photos/seed/merlot-giaretta/400/600',
  },
  {
    id: 55,
    name: 'Miolo Seleção Pinot Grigio & Riesling',
    type: 'Branco',
    region: 'Campanha Gaúcha, Brasil',
    price: 30.05,
    imageUrl: 'https://picsum.photos/seed/miolo-pinot-grigio-riesling/400/600',
  },
  {
    id: 56,
    name: 'Miolo Single Vineyard Cabernet Franc',
    type: 'Tinto',
    region: 'Campanha Gaúcha, Brasil',
    price: 71.39,
    imageUrl: 'https://picsum.photos/seed/miolo-single-cab-franc/400/600',
  },
  {
    id: 57,
    name: 'Mon Basset Classique Aoc',
    type: 'Tinto',
    region: 'França',
    price: 65.82,
    imageUrl: 'https://picsum.photos/seed/mon-basset-classique/400/600',
  },
  {
    id: 58,
    name: 'Moscato Giaretta',
    type: 'Branco',
    region: 'Serra Gaúcha, Brasil',
    price: 29.68,
    imageUrl: 'https://picsum.photos/seed/moscato-giaretta/400/600',
  },
  {
    id: 59,
    name: 'Mr. Rabbit Pinot Noir',
    type: 'Tinto',
    region: "Pays d'Oc, França",
    price: 70.67,
    imageUrl: 'https://picsum.photos/seed/mr-rabbit-pinot-noir/400/600',
  },
  {
    id: 60,
    name: 'Mr. Rabbit Tinto Pays D’OC IGP Cabernet Sauvignon',
    type: 'Tinto',
    region: "Pays d'Oc, França",
    price: 61.05,
    imageUrl: 'https://picsum.photos/seed/mr-rabbit-cabernet/400/600',
  },
  {
    id: 61,
    name: 'Mr. Rabbit Tinto Pays D’OC IGP Syrah',
    type: 'Tinto',
    region: "Pays d'Oc, França",
    price: 62.0,
    imageUrl: 'https://picsum.photos/seed/mr-rabbit-syrah/400/600',
  },
  {
    id: 62,
    name: 'Mucho Más',
    type: 'Tinto',
    region: 'La Mancha, Espanha',
    price: 71.51,
    imageUrl: 'https://picsum.photos/seed/mucho-mas/400/600',
  },
  {
    id: 63,
    name: 'Mythic Cellars - Mountain - Petit Verdot',
    type: 'Tinto',
    region: 'Argentina',
    price: 73.89,
    imageUrl: 'https://picsum.photos/seed/mythic-cellars-petit-verdot/400/600',
  },
  {
    id: 64,
    name: 'Namaqua - Merlot',
    type: 'Tinto',
    region: 'África do Sul',
    price: 55.9,
    imageUrl: 'https://picsum.photos/seed/namaqua-merlot/400/600',
  },
  {
    id: 65,
    name: 'Navalheiro Regional Trasmontano',
    type: 'Tinto',
    region: 'Trás-os-Montes, Portugal',
    price: 52.24,
    imageUrl: 'https://picsum.photos/seed/navalheiro-trasmontano/400/600',
  },
  {
    id: 66,
    name: 'New Roads Blend',
    type: 'Tinto',
    region: 'África do Sul',
    price: 26.54,
    imageUrl: 'https://picsum.photos/seed/new-roads-blend/400/600',
  },
  {
    id: 67,
    name: 'No Branding No cry',
    type: 'Tinto',
    region: 'Portugal',
    price: 63.05,
    imageUrl: 'https://picsum.photos/seed/no-branding-no-cry/400/600',
  },
  {
    id: 68,
    name: 'OVNIH SPARKLING WINE MOSCATEL',
    type: 'Espumante',
    region: 'Portugal',
    price: 13.78,
    imageUrl: 'https://picsum.photos/seed/ovnih-sparkling-moscatel/400/600',
  },
  {
    id: 69,
    name: 'Paso de Los Andes Reserva Pinot Noir',
    type: 'Tinto',
    region: 'Vale Central, Chile',
    price: 45.28,
    imageUrl: 'https://picsum.photos/seed/paso-andes-reserva-pinot/400/600',
  },
  {
    id: 70,
    name: 'Paso de Los Andes RESERVA Tinto',
    type: 'Tinto',
    region: 'Vale Central, Chile',
    price: 44.1,
    imageUrl: 'https://picsum.photos/seed/paso-andes-reserva-tinto/400/600',
  },
  {
    id: 71,
    name: 'PASO DE LOS ANDES VARIETAL CARMENERE',
    type: 'Tinto',
    region: 'Vale Central, Chile',
    price: 48.25,
    imageUrl: 'https://picsum.photos/seed/paso-andes-carmenere/400/600',
  },
  {
    id: 72,
    name: 'Pássaro da Lua Blend',
    type: 'Tinto',
    region: 'Brasil',
    price: 152.25,
    imageUrl: 'https://picsum.photos/seed/passaro-da-lua-blend/400/600',
  },
  {
    id: 73,
    name: 'Pássaro da Lua Merlot',
    type: 'Tinto',
    region: 'Brasil',
    price: 152.25,
    imageUrl: 'https://picsum.photos/seed/passaro-da-lua-merlot/400/600',
  },
  {
    id: 74,
    name: 'Pássaro da Lua Tannat',
    type: 'Tinto',
    region: 'Brasil',
    price: 152.25,
    imageUrl: 'https://picsum.photos/seed/passaro-da-lua-tannat/400/600',
  },
  {
    id: 75,
    name: 'Passo de Los Andes Moskato',
    type: 'Branco',
    region: 'Chile',
    price: 30.62,
    imageUrl: 'https://picsum.photos/seed/passo-andes-moskato/400/600',
  },
  {
    id: 76,
    name: 'Pescada BLEND VERDE',
    type: 'Branco',
    region: 'Portugal',
    price: 76.76,
    imageUrl: 'https://picsum.photos/seed/pescada-blend-verde/400/600',
  },
  {
    id: 77,
    name: 'Pode Ser',
    type: 'Tinto',
    region: 'Portugal',
    price: 44.54,
    imageUrl: 'https://picsum.photos/seed/pode-ser/400/600',
  },
  {
    id: 78,
    name: 'Porta 6',
    type: 'Tinto',
    region: 'Lisboa, Portugal',
    price: 50.78,
    imageUrl: 'https://picsum.photos/seed/porta-6/400/600',
  },
  {
    id: 79,
    name: 'Profugo Malbec',
    type: 'Tinto',
    region: 'Mendoza, Argentina',
    price: 44.8,
    imageUrl: 'https://picsum.photos/seed/profugo-malbec/400/600',
  },
  {
    id: 80,
    name: 'Profugo Sauvignon Blanc',
    type: 'Branco',
    region: 'Mendoza, Argentina',
    price: 44.8,
    imageUrl: 'https://picsum.photos/seed/profugo-sauvignon-blanc/400/600',
  },
  {
    id: 81,
    name: 'Rosso Toscana Igt Rifugio Del Vescovo',
    type: 'Tinto',
    region: 'Toscana, Itália',
    price: 89.61,
    imageUrl: 'https://picsum.photos/seed/rosso-toscana-igt/400/600',
  },
  {
    id: 82,
    name: 'ROUGE PISCINE',
    type: 'Tinto',
    region: 'França',
    price: 36.83,
    imageUrl: 'https://picsum.photos/seed/rouge-piscine/400/600',
  },
  {
    id: 83,
    name: 'Signos',
    type: 'Tinto',
    region: 'Argentina',
    price: 41.39,
    imageUrl: 'https://picsum.photos/seed/signos/400/600',
  },
  {
    id: 84,
    name: 'SINGLE VINEYARD Pinot Noir',
    type: 'Tinto',
    region: 'Brasil',
    price: 61.18,
    imageUrl: 'https://picsum.photos/seed/single-vineyard-pinot-noir/400/600',
  },
  {
    id: 85,
    name: 'SINGLE VINEYARD Touriga Nacional',
    type: 'Tinto',
    region: 'Brasil',
    price: 61.18,
    imageUrl: 'https://picsum.photos/seed/single-vineyard-touriga/400/600',
  },
  {
    id: 86,
    name: 'Sutter Home',
    type: 'Rosé',
    region: 'Califórnia, EUA',
    price: 82.81,
    imageUrl: 'https://picsum.photos/seed/sutter-home/400/600',
  },
  {
    id: 87,
    name: 'Tannat Giaretta',
    type: 'Tinto',
    region: 'Serra Gaúcha, Brasil',
    price: 47.79,
    imageUrl: 'https://picsum.photos/seed/tannat-giaretta/400/600',
  },
  {
    id: 88,
    name: 'TARANI MALBEC CAHORS',
    type: 'Tinto',
    region: 'Cahors, França',
    price: 64.5,
    imageUrl: 'https://picsum.photos/seed/tarani-malbec-cahors/400/600',
  },
  {
    id: 89,
    name: 'Torre Romanica PRIMITIVO',
    type: 'Tinto',
    region: 'Puglia, Itália',
    price: 63.38,
    imageUrl: 'https://picsum.photos/seed/torre-romanica-primitivo/400/600',
  },
  {
    id: 90,
    name: 'Torre Romanica Sangiovese',
    type: 'Tinto',
    region: 'Itália',
    price: 45.44,
    imageUrl: 'https://picsum.photos/seed/torre-romanica-sangiovese/400/600',
  },
  {
    id: 91,
    name: 'Vezzani Montepulciano',
    type: 'Tinto',
    region: 'Abruzzo, Itália',
    price: 80.7,
    imageUrl: 'https://picsum.photos/seed/vezzani-montepulciano/400/600',
  },
  {
    id: 92,
    name: 'Vezzani Negroamaro Rosato',
    type: 'Rosé',
    region: 'Puglia, Itália',
    price: 77.92,
    imageUrl: 'https://picsum.photos/seed/vezzani-negroamaro-rosato/400/600',
  },
  {
    id: 93,
    name: "Vezzani Nero D'Avola",
    type: 'Tinto',
    region: 'Sicília, Itália',
    price: 80.67,
    imageUrl: 'https://picsum.photos/seed/vezzani-nero-davola/400/600',
  },
  {
    id: 94,
    name: 'Vezzani Nero di Troia',
    type: 'Tinto',
    region: 'Puglia, Itália',
    price: 83.35,
    imageUrl: 'https://picsum.photos/seed/vezzani-nero-di-troia/400/600',
  },
  {
    id: 95,
    name: 'Vezzani Trebbiano',
    type: 'Branco',
    region: 'Abruzzo, Itália',
    price: 50.88,
    imageUrl: 'https://picsum.photos/seed/vezzani-trebbiano/400/600',
  },
  {
    id: 96,
    name: 'VINHO ALMADEN TINTO SECO MERLOT',
    type: 'Tinto',
    region: 'Serra Gaúcha, Brasil',
    price: 28.0,
    imageUrl: 'https://picsum.photos/seed/almaden-merlot/400/600',
  },
  {
    id: 97,
    name: 'VINHO ALMADEN TINTO SECO Tempranillo',
    type: 'Tinto',
    region: 'Serra Gaúcha, Brasil',
    price: 30.07,
    imageUrl: 'https://picsum.photos/seed/almaden-tempranillo/400/600',
  },
  {
    id: 98,
    name: 'VINHO MIOLO SELECAO TINTO SECO CABERNET/MERLOT',
    type: 'Tinto',
    region: 'Campanha Gaúcha, Brasil',
    price: 19.21,
    imageUrl: 'https://picsum.photos/seed/miolo-selecao-tinto/400/600',
  },
  {
    id: 99,
    name: 'VINHO MIOLO WILD TINTO SECO GAMAY',
    type: 'Tinto',
    region: 'Campanha Gaúcha, Brasil',
    price: 56.71,
    imageUrl: 'https://picsum.photos/seed/miolo-wild-gamay/400/600',
  },
  {
    id: 100,
    name: "WINEMAKER'S SECRET BARREL",
    type: 'Tinto',
    region: 'Califórnia, EUA',
    price: 56.09,
    imageUrl: 'https://picsum.photos/seed/winemakers-secret-barrel/400/600',
  },
  {
    id: 101,
    name: 'Yali - Wild Swan Sauvignon Blanc',
    type: 'Branco',
    region: 'Vale Central, Chile',
    price: 52.62,
    imageUrl: 'https://picsum.photos/seed/yali-wild-swan-sauvignon/400/600',
  },
  {
    id: 102,
    name: 'Plexus Espumante Rosé',
    type: 'Espumante',
    region: 'Brasil',
    price: 37.17,
    imageUrl: 'https://picsum.photos/seed/plexus-espumante-rose/400/600',
  },
  {
    id: 103,
    name: 'Plexus Espumante Branco',
    type: 'Espumante',
    region: 'Brasil',
    price: 37.17,
    imageUrl: 'https://picsum.photos/seed/plexus-espumante-branco/400/600',
  },
  {
    id: 104,
    name: 'Gretus Tempranillo',
    type: 'Tinto',
    region: 'Espanha',
    price: 41.34,
    imageUrl: 'https://picsum.photos/seed/gretus-tempranillo/400/600',
  },
  {
    id: 105,
    name: 'Porto Dom Manuel',
    type: 'Tinto',
    region: 'Douro, Portugal',
    price: 97.83,
    imageUrl: 'https://picsum.photos/seed/porto-dom-manuel/400/600',
  },
  {
    id: 106,
    name: 'Fincas Privada Bornarda',
    type: 'Tinto',
    region: 'Argentina',
    price: 41.48,
    imageUrl: 'https://picsum.photos/seed/fincas-privada-bornarda/400/600',
  },
];
